# Generated by Django 5.2.5 on 2025-08-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='profile_photo',
            new_name='avatar',
        ),
    ]
