# Generated by Django 5.2.5 on 2025-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='report_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
