# Generated by Django 5.2.5 on 2025-09-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancerequest',
            old_name='remarks',
            new_name='rejection_reason',
        ),
        migrations.RenameField(
            model_name='reimbursement',
            old_name='remarks',
            new_name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='approver',
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='current_approver_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='current_approver_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='report_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
