# Generated by Django 5.2.5 on 2025-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0002_rename_remarks_advancerequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('reimbursement', 'Reimbursement'), ('advance', 'Advance')], max_length=20)),
                ('request_id', models.IntegerField()),
                ('approver_id', models.CharField(max_length=50)),
                ('approver_name', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Xpensure_approvalhistory',
            },
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='approved_by_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='approved_by_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='final_approver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='approved_by_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='approved_by_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='final_approver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
