# Generated by Django 5.2.5 on 2025-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0002_rename_profile_photo_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='currentStep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='payments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='currentStep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='payments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
