# Generated by Django 5.2.5 on 2025-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0003_approvalhistory_advancerequest_approved_by_ceo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Common', 'Common'), ('HR', 'HR'), ('CEO', 'CEO'), ('Finance Verification', 'Finance Verification'), ('Finance Payment', 'Finance Payment')], default='Common', max_length=25),
        ),
    ]
