# Generated by Django 5.2.5 on 2025-09-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0003_advancerequest_currentstep_advancerequest_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Common', 'Common'), ('HR', 'HR'), ('CEO', 'CEO'), ('Finance', 'Finance')], default='Common', max_length=20),
        ),
    ]
