# Generated by Django 5.2.5 on 2025-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0003_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(default='Reimbursement', max_length=50),
        ),
        migrations.DeleteModel(
            name='Reimbursement',
        ),
    ]
