# Generated by Django 5.2.5 on 2025-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0004_remove_employee_username_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
