# Generated by Django 5.2.5 on 2025-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0004_alter_request_request_type_delete_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
