# Generated by Django 5.2.7 on 2025-12-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='approved_by_hr',
            field=models.BooleanField(default=False),
        ),
    ]
