# Generated by Django 5.2.5 on 2025-09-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0005_employee_reporting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='reporting_id',
            new_name='report_to',
        ),
    ]
