# Generated by Django 5.2.5 on 2025-09-03 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xpensure', '0006_rename_reporting_id_employee_report_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='employee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='advances',
                to=settings.AUTH_USER_MODEL,
                to_field="employee_id",
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='report_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subordinates',
                to=settings.AUTH_USER_MODEL,
                to_field="employee_id",
            ),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='employee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reimbursements',
                to=settings.AUTH_USER_MODEL,
                to_field="employee_id",
            ),
        ),
    ]
